title: TradeHero
default_lang: en
author:
  name: 'Viraj Kothalawala'
  email: viraj@tradehero.mobi
taxonomies:
  - category
  - tag
metadata:
  description: 'Trade virtual stocks, compete with your friends, get expert stock tips and earn extra cash all at the same time! TradeHero is a mobile stock market simulation app that lets you learn about trading without any risk.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "https://www.facebook.com/TradeHero"
     icon: facebook
  -  url: "https://twitter.com/TradeHeroMobile"
     icon: twitter
  -  url: "https://www.youtube.com/user/TradeHeroMobile"
     icon: youtube  
  -  url: "https://medium.com/tradehero"
     icon: medium
